AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-compression-service

  Sample SAM Template for image-compression-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Resources:
  ImageRepoBucket: 
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "image-repo-bucket"

  ImageCompressorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-compressor-lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImageRepoBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix 
                  Value: raw   
      Role: arn:aws:iam::913923565754:role/AWSLambdaImageRepoRole
        
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ImageCompressorFunction:
    Description: ImageCompressorFunction Lambda Function ARN
    Value: !GetAtt ImageCompressorFunction.Arn
